### ISSUE TITLE
Create organization

### ISSUE THREAD

**Issue by HriBB** [react-paper/react-paper-bindings#20]
It seems that the maintainers of the PaperJS are not interested in adding this library to the paperjs organization, so I think we should create a new one. Or I can just add people as owners/maintainers. I don't really care, as long as it benefits us all.

@andriibuts and @kota65535 what do you guys think? I don't have much experience maintaining a lib, and even less time, so if you guys can help me out, that would be great.

**Comment by andriibuts** [comment]
I've already created an empty `react-paper-renderer` npm package and it seems term `renderer` is more widespread in the community, so I'd suggest to either create an organization with name `react-paper-renderer` or just rename this package.

**Comment by kota65535** [comment]
According to [this page](https://github.com/chentsulin/awesome-react-renderer), `react-paper-renderer` or more simply `react-paper` seem to be possible names. 
It sounds good for me to create organization.

**Comment by andriibuts** [comment]
Unfortunately, [react-paper](https://www.npmjs.com/package/react-paper) name for npm module has already been taken

**Comment by HriBB** [comment]
I like `react-paper-renderer`. I think we should use that, since `react-paper` is not available. So how do we proceed? Do we rename this repo or start a new one? I can also transfer ownership, right? Anyway, I would still like to be a maintainer, because I want to learn this kind of stuff ;) Also, I made some commits (remove matrix from the View), that are not yet published as a release, just wanted to mention it. And I have some ideas on how to improve the tool handling and <canvas> rendering. Need to get it out into black on white :)

**Comment by andriibuts** [comment]
I've just created an organization https://github.com/react-paper and invited you guys with an `owner` role.

Here is an [instruction how to transfer the project to the organization](https://help.github.com/articles/transferring-a-repository-owned-by-your-personal-account/#transferring-to-an-organization) but I'm not sure whether it's possible to rename repository while transferring it so I've also created an empty one - https://github.com/react-paper/react-paper-renderer.

@HriBB, you could try to transfer your repo, or just push code into new one.

**Comment by HriBB** [comment]
OK I transfered the project to the organization!
