### ISSUE TITLE
Responsive Shapes

### ISSUE THREAD

**Issue by mohannadsalem** [react-paper/react-paper-bindings#35]
I am trying to change some points in a couple of shapes from a controller outside the paperjs  view passing them through props to create the new layout but the points in any shape are not responsive to any change. Although when i printed the data object in the console the points were changed. Any Idea Why this behaviour happens ?!

**Comment by HriBB** [comment]
@mohannadsalem please provide some more information. Also check out [version 3](https://github.com/react-paper/react-paper-bindings/tree/v3), which should be much improved. I am closing this issue, because this is not a bug in `react-paper-bindings`. Feel free to reopen if you think otherwise.
